# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ismael Trascastro
email: itrascastro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Symfony and Zend Framework Instructor. PHP, MVC, Doctrine, POO, ...
  I also created xenframework.com, a PHP MVC Framework
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title/
url: "https://itrascastro.github.io" # the base hostname & protocol for your site
twitter_username: itrascastro
github_username:  itrascastro

paginate: 4

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
